name: simply-typed-ext
version: 0.1.0.0
github: "mbg/simply-typed-ext"
author: "Michael B. Gale"
maintainer: "github@michael-gale.co.uk"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/mbg/simply-typed-ext#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- directory
- mtl

library:
  source-dirs: src
  build-tools:
    - alex
    - happy

executables:
  simply-typed-ext-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - simply-typed-ext
